### ISSUE TITLE
Use the Compact Structure for recognition

### ISSUE THREAD

**Issue by ghost** [AutoML-4Paradigm/AutoSTR#1]
@quanmingyao @huizhang0110 

After searching and retraining a compact structure, 
how can i use the model to recognize the images in a folder. inferincing script
Does AutoSTR work on words only, or can it be trained on text-lines
Can inferencing/text recognition be done using cpu

**Comment by huizhang0110** [comment]
Hi, @deepseek. Thanks for your comment. We aim to find a backbone for better feature sequences extracting, which can theoretically adapt to most recognition pipeline and hardware.

**Comment by ghost** [comment]
- inferencing script
- can i search for a backbone that uses textlines instead of words

**Comment by huizhang0110** [comment]
Hi, for inferencing script, you can refer to the evaluation part in `main.py`. For text line level annotation, the width axis could have a larger variance than the word level.  Backbone searching space & algorithm doesn't have specific fixed constrain in width, so our method will not be affected by text lines or words level annotation theoretically, which both are character sequences. In order to use in the text lines annotation dataset, you just need to do some engineering adaptation, for example, variable-width input data loader and STN Module.
